#soy un demo de un archivo yml
name: reto04
on: 
   workflow_dispatch
jobs: 
  Job1:
   runs-on: ubuntu-latest
   steps:
    - name: step1 
      run: echo 'hola'
    - name: step2
      run: echo 'Paso 02'
jobs:
  Job2:
   runs-on: ubuntu-latest
   steps:
    - name: Ship ituses: mscoutermarsh/cowsays-action@masterwith:
      text: 'Generar mas pasos: 'red'
